package:
  name: parmed
  version: !!str 3.1.0

source:
  fn: ParmEd-3.1.0.tar.gz
  url: https://github.com/ParmEd/ParmEd/archive/3.1.0.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - numpy >=1.14
    - setuptools

  run:
    - python
    - numpy >=1.14
    - pandas

about:
  home: http://parmed.github.io/ParmEd
  license: LGPL
  license_file: GNU_LGPL_v2
  summary: A package for parsing, interconverting, manipulating, and simulating biomolecular simulations with many packages
