package:
  name: openmm
  version: 7.4.0

source:
  git_url: https://github.com/pandegroup/openmm.git
  git_tag: 81bad1b

  patches:
    #- silent-cmake.patch
    - silent-doxygen.patch
    - silent-latexpdf.patch

extra:
  upload: rccuda{{ CUDA_SHORT_VERSION }}{{ ",rc" if CUDA_SHORT_VERSION == "92" else ""}}
  force_upload: False

build:
  number: 0
  skip: True # [win]
  detect_binary_files_with_prefix: False
  string: py{{py}}_cuda{{ CUDA_SHORT_VERSION }}_rc_1
  # Inherit the following environment variables in build.sh call
  script_env:
   - CUDA_VERSION
   - CUDA_SHORT_VERSION
   - CUDAPATH

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # on windows, need to install cmake manually
    - cmake     [not win]
    - jom       [win]
    - python
    # Pin fftw3f to 3.3.3 to work around OSX py34 issues
    - fftw3f ==3.3.3 [osx]
    - fftw3f ==3.3.4 [win or linux]
    # swig is pinned to use omnia swig 3.0.8
    - swig ==3.0.8
    # on osx, need to install doxygen manually
    - doxygen   [not osx]
    # for building docs
    #- sphinx
    #- sphinxcontrib-bibtex
    #- sphinxcontrib-lunrsearch >=0.3
    #- sphinxcontrib-autodoc_doxygen
    - lxml
    - numpy
    # Get clang from conda-forge
    - clangdev ==6.0.0 [linux and not ppc64le]
    #- gcc [ppc64le]
    # Required for sphinx
    #- latexmk [not win]
    - cython

  run:
    - python
    - fftw3f
    - numpy
    - cython

about:
  home: http://openmm.org
  license: LGPL and MIT
  summary: A high performance toolkit for molecular simulation.
